# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [1]:
from numpy import * #Load all the numpy packages

In [2]:
zeros?

### A Note About "import as" & 'Name spaces'

    import * 
This loads all submodules. Note: this is a waste of memory when incorporated into deployed code. 
We'll use it here by example - it's fine to use for learning purposes and legibility.

As we'll see later, the proper convention is to use:

    import numpy as np
    
And then to specifically call needed methods:

![](http://bit.do/cBuMz)

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [81]:
# A simple 1-dimensional array:
a = zeros((3))
print(a)
a.shape

[ 0.  0.  0.]


(3,)

In [82]:
b = ones((2,3))
print(b.shape)
print(b)

(2, 3)
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [83]:
# Note the way each array is printed:
c = random.randint(1,10,(2,3,4))
print(c.shape)
c

(2, 3, 4)


array([[[7, 5, 1, 7],
        [1, 7, 3, 2],
        [6, 7, 3, 4]],

       [[9, 9, 4, 2],
        [6, 8, 1, 5],
        [1, 9, 4, 6]]])

In [84]:
demo = arange(24)

In [85]:
arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [86]:
demo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [87]:
demo.shape

(24,)

In [88]:
demo_2d = demo.reshape(-1, 2)
demo_2d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [89]:
demo_2d.shape

(12, 2)

In [90]:
demo_3d = demo_2d.reshape(-1, 2, 3)
demo_3d.shape


(4, 2, 3)

In [91]:
demo_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

### Arithmetic in arrays is element wise

In [92]:
a = array( [20,30,40,50])
b = arange( 4 )
print a
print b

[20 30 40 50]
[0 1 2 3]


In [93]:
c = a-b
c

array([20, 29, 38, 47])

In [94]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [95]:
# one-dimensional arrays work like lists:
a = arange(10)**2

In [96]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [97]:
a[:8]

array([ 0,  1,  4,  9, 16, 25, 36, 49])

### Multidimensional arrays use (row,column) tuples counting from 0

In [98]:
b = random.randint(1,100,(4,4))

In [99]:
b

array([[66, 49, 74, 30],
       [35, 85, 94, 98],
       [30, 75, 58, 61],
       [46, 97, 44, 95]])

In [100]:
# Guess the output
b[2,3]

61

In [101]:
b[0,0]

66

In [102]:
b[0:3,1]

array([49, 85, 75])

In [103]:
b[:,1]

array([49, 85, 75, 97])

In [104]:
b[1:3,:]

array([[35, 85, 94, 98],
       [30, 75, 58, 61]])